# api register
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
	"name":"Data test",
    "phone":"6",
    "password":"6",
    "dateOfBirth":"2002-08-14",
    "gender":"male"
}
###
# api login
POST  http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "phone":"1",
    "password":"1"
}

# logout
###
POST http://localhost:8000/api/v1/auth/logout
###
# lấy refreshToekn từ cookies
GET http://localhost:8000/api/v1/auth/refreshToken